general:
  package: 'sonarr'
  name: 'Sonarr'
  version: '2.0.0.3953-1'
  depends:
  - 'mono (>= 3.10)'
  conflicts: []
  developer: 'Sonarr'
  email: 'fboudra+adm@gmail.com'
  website: 'https://sonarr.tv/'
  architecture: 'x86-64'
  firmware: '2.5.0'
  maintainer: 'Fathi Boudra'
  model:
  - '50xx'
  - '51xx'
adm-desktop:
  app:
    type: 'custom'
    protocol: 'http'
    port: 8989
    url: '/'
  privilege:
    accessible: 'users'
    customizable: true
register:
  prerequisites:
    enable-service: []
    restart-service: []
  boot-priority:
    start-order: 20
    stop-order: 80
  port: [8989]
